#!/bin/sh

set -e


# Remove .desktop file

if [ "$1" = "configure" ] && [ -x "`which xdg-desktop-menu 2>/dev/null`" ] ; then
    xdg-desktop-menu uninstall --novendor /usr/share/applications/lmxconverter.desktop || true
fi

